/* ============== DATA ============== */
const DATA = [
{id:"msg", icon:"💬", title:"Messaggistica cifrata", intro:"Il primo gesto, quello che protegge più in fretta: lasciare WhatsApp, Messenger e Telegram per una messaggistica davvero cifrata e, quando possibile, open-source.", items:[
  {id:"signal", name:"Signal", flag:"🇺🇸 open-source", lvl:["g","y","r"], tag:"Sostituisce WhatsApp", desc:"Messaggistica cifrata per testi, chiamate, video e gruppi. Sostituto diretto di WhatsApp, stessa semplicità.", why:"Cifratura end-to-end di default, no-profit, protocollo verificato che è lo standard mondiale. Il team ha promesso di lasciare l'UE piuttosto che installare uno scan.", steps:["Installa da signal.org (App Store, Play Store o APK diretto)","Conferma il numero via SMS, imposta un PIN","Impostazioni > Privacy: crea uno username per nascondere il numero, attiva il blocco registrazione","Invita i tuoi contatti"], link:"https://signal.org"},
  {id:"simplex", name:"SimpleX Chat", flag:"🌍 open-source", lvl:["y","r"], tag:"Senza identificativo", desc:"Messaggistica cifrata senza account, senza numero, senza identificativo. Ci si collega con un link o un QR code.", why:"Per progettazione, nemmeno i server sanno chi parla con chi. È l'opzione più protettiva oggi contro la correlazione dei metadati.", steps:["Installa da simplex.chat (F-Droid, Play Store, App Store o APK)","Scegli un nome visibile locale (mai il vero nome, resta sul dispositivo)","Per aggiungere un contatto condividi un link d'invito monouso o un QR","Attiva il blocco con codice; opzionale: server SMP tuoi"], link:"https://simplex.chat"},
  {id:"session", name:"Session", flag:"🌍 open-source", lvl:["y","r"], tag:"Senza numero", desc:"Cifratura in stile Signal ma senza numero di telefono, con instradamento onion.", why:"La tua identità è un 'Session ID' casuale. Il traffico passa su rete decentralizzata (Lokinet) che riduce fortemente i metadati.", steps:["Installa da getsession.org (tutte le piattaforme)","'Create account' genera il Session ID e una frase di recupero","Annota la frase su carta: è l'unica chiave del tuo account","Condividi il Session ID (o QR) con i tuoi contatti"], link:"https://getsession.org"},
  {id:"briar", name:"Briar", flag:"Android · open-source", lvl:["r"], tag:"Offline / P2P", desc:"Messaggistica peer-to-peer che funziona senza internet: Bluetooth, Wi-Fi Direct o Tor.", why:"Nessun server, quindi niente da spegnere o sequestrare. Resiste a blackout di rete e censura.", steps:["Installa da briarproject.org o F-Droid (niente iOS)","Crea un account locale (nickname + password)","Aggiungi un contatto vicino scannerizzando il suo QR, o a distanza via link","Con rete assente, attiva il Bluetooth: i messaggi saltano da dispositivo a dispositivo"], link:"https://briarproject.org"},
  {id:"bitchat", name:"Bitchat", flag:"🌍 open-source", lvl:["r"], tag:"Mesh Bluetooth", desc:"Messaggistica mesh di Jack Dorsey: i telefoni vicini si passano i messaggi di mano in mano, senza internet, server o account.", why:"Cifratura end-to-end (AES-256-GCM) e una 'modalità panico' che cancella tutto in tre tap. Attenzione: non ha ricevuto revisione di sicurezza esterna, non fondarci vite reali per ora.", steps:["Installa da App Store (iOS) o APK/GitHub (Android)","Apri l'app e scegli un pseudonimo, nessun account da creare","I dispositivi vicini si scoprono da soli via Bluetooth","In caso di pericolo, tripla-tap sul logo per cancellare tutto"], link:"#"},
  {id:"molly", name:"Molly", flag:"Android · open-source", lvl:["r"], tag:"Signal indurito", desc:"Versione indurita di Signal per Android, compatibile con la stessa rete.", why:"Database cifrato a riposo, blocco automatico, variante FOSS interamente senza servizi Google.", steps:["Aggiungi il repo Molly in F-Droid o prendi l'APK da molly.im","Scegli Molly-FOSS per zero dipendenze Google","Registrati col numero (stessa rete di Signal)","Imposta password del database e blocco automatico"], link:"https://molly.im"}
]},
{id:"email", icon:"✉️", title:"Email cifrata & PGP", intro:"Gmail legge le tue email e vive negli USA, sotto giurisdizione 'Five Eyes'. Lasciare Gmail/Outlook è un guadagno enorme per uno sforzo minimo.", items:[
  {id:"protonmail", name:"Proton Mail", flag:"🇨🇭 open-source · OpenPGP", lvl:["g","y","r"], tag:"Sostituisce Gmail", desc:"Casella cifrata che sostituisce Gmail o Outlook, e l'account cardine di tutto l'ecosistema Proton.", why:"Sede in Svizzera, fuori giurisdizione 'Five Eyes'. Compatibile OpenPGP: cifratura automatica tra account Proton e verso altri servizi PGP.", steps:["Crea un account su proton.me (il piano gratuito basta per iniziare)","Importa vecchi messaggi e contatti con Easy Switch","Attiva un forward da Gmail e avvisa i contatti del nuovo indirizzo","Installa l'app mobile, attiva la 2FA, usa Proton Bridge se vuoi Thunderbird"], link:"https://proton.me/mail"},
  {id:"tuta", name:"Tuta", flag:"🇩🇪 open-source · post-quantistico", lvl:["g","y"], tag:"Sostituisce Gmail", desc:"Servizio email tedesco, interamente open-source e senza alcun servizio Google.", why:"Cifra anche oggetto e parte dei metadati, con cifratura resistente al calcolo quantistico. Giurisdizione UE.", steps:["Crea un account su tuta.com e installa l'app (disponibile su F-Droid)","Per scrivere cifrato a chi non usa Tuta: clic sul lucchetto, imposta una password, condivisa su un altro canale","Attiva la 2FA"], link:"https://tuta.com"},
  {id:"mailboxposteo", name:"mailbox.org · Posteo", flag:"🇩🇪 UE · PGP", lvl:["g"], tag:"Mail classica etica", desc:"Due provider email europei, etici e economici, con supporto PGP lato server.", why:"Rispettosi di privacy ed ecologia, su standard aperti (IMAP, PGP). Funzionano con qualsiasi client di posta.", steps:["Crea un account (a pagamento, 1-3€/mese)","Attiva la cifratura PGP lato server (funzione 'Guard' su mailbox.org)","Configura l'account su Thunderbird o l'app mobile che preferisci"], link:"https://mailbox.org"}
]},
{id:"browser", icon:"🌐", title:"Browser & ricerca", intro:"Chrome è una spia pubblicitaria. Google Search profila ogni ricerca. Si sostituiscono entrambi.", items:[
  {id:"mullvadbrowser", name:"Mullvad Browser", flag:"🇸🇪 open-source", lvl:["y","r"], tag:"Anti-fingerprint", desc:"Il browser del Tor Browser, ma senza la rete Tor: da usare col tuo VPN per un computer difficile da tracciare.", why:"Sviluppato con il Tor Project: tutti gli utenti presentano la stessa impronta digitale. Invece di essere unico e tracciabile, ti confondi nella massa.", steps:["Scaricalo da mullvad.net/browser","Usalo così com'è, senza personalizzarlo: ogni estensione o impostazione aggiunta ti rende di nuovo identificabile","Abbinalo al tuo VPN per mascherare anche l'IP"], link:"https://mullvad.net/browser"},
  {id:"firefox", name:"Firefox (indurito)", flag:"🌍 open-source", lvl:["g","y","r"], tag:"Sostituisce Chrome", desc:"Il browser libero di riferimento per un uso quotidiano rispettoso della privacy.", why:"A differenza di Chrome (spia pubblicitaria di Google), Firefox è sviluppato da una fondazione senza interesse a profilarti.", steps:["Installa Firefox da mozilla.org/firefox","Aggiungi l'estensione uBlock Origin","Impostazioni privacy su 'Rigorosa', disattiva telemetria, cancella cookie alla chiusura. Per andare oltre, applica la guida arkenfox"], link:"https://www.mozilla.org/firefox"},
  {id:"brave", name:"Brave", flag:"🌍 open-source", lvl:["g"], tag:"Blocca tutto di default", desc:"Browser basato su Chromium che blocca pubblicità e tracker di default, con una finestra privata connessa a Tor.", why:"L'opzione più semplice per chi arriva da Chrome: stessa ergonomia, senza il tracciamento. Accesso Tor in un click.", steps:["Installa Brave da brave.com","Imposta gli Shields su 'aggressivo', disattiva Brave Rewards se non ti interessano","Per Tor: menu > 'Nuova finestra privata con Tor'"], link:"https://brave.com"},
  {id:"ublock", name:"uBlock Origin", flag:"🌍 open-source", lvl:["g","y","r"], tag:"Estensione", desc:"L'estensione che blocca pubblicità, tracker e script spia. Il gesto più redditizio, in dieci secondi.", why:"La pubblicità online è il principale vettore di sorveglianza e profilazione. Bloccarla taglia gran parte del tracciamento.", steps:["Apri lo store estensioni del tuo browser e cerca 'uBlock Origin' (l'originale, di Raymond Hill)","Installalo. Funziona subito, nessuna configurazione necessaria"], link:"https://ublockorigin.com"},
  {id:"ddg", name:"DuckDuckGo · Brave Search · SearXNG", flag:"Motori di ricerca", lvl:["g","y"], tag:"Sostituisce Google Search", desc:"Motori di ricerca che non profilano ogni query, a differenza di Google.", why:"DuckDuckGo e Brave Search non conservano cronologia legata alla tua identità. SearXNG è un metamotore auto-ospitabile.", steps:["Nelle impostazioni del browser cambia il motore predefinito","Per SearXNG: usa un'istanza pubblica (elenco su searx.space) o ospita la tua"], link:"https://duckduckgo.com"}
]},
{id:"dns", icon:"🔒", title:"DNS cifrato", intro:"Il DNS traduce un nome di sito in un indirizzo. Di default lo gestisce il tuo provider internet, che vede quindi ogni sito che visiti, anche in HTTPS. Cifrarlo è un'impostazione discreta ma tra le più efficaci.", items:[
  {id:"quad9", name:"Quad9", flag:"🇨🇭 non-profit", lvl:["g","y","r"], tag:"Anti-malware", desc:"Un resolver DNS cifrato, svizzero e no-profit, che blocca anche i domini malevoli conosciuti.", why:"Giurisdizione svizzera, nessuna conservazione del tuo IP, protezione da phishing e malware.", steps:["Android: Impostazioni > Rete > DNS privato > inserisci dns.quad9.net","iPhone/Mac: installa il profilo DoH da quad9.net"], link:"https://quad9.net"},
  {id:"mullvaddns", name:"Mullvad DNS · NextDNS", flag:"Filtraggio di rete", lvl:["y"], tag:"", desc:"Due resolver cifrati che bloccano anche pubblicità e tracker per l'intero dispositivo.", why:"Mullvad DNS (Svezia, no-log) è gratuito. NextDNS è molto personalizzabile ma è basato USA e logga di default (da disattivare).", steps:["Mullvad DNS: usa l'indirizzo su mullvad.net/help/dns come DNS privato","NextDNS: crea un profilo su nextdns.io, disattiva la registrazione, applica ai dispositivi"], link:"https://mullvad.net/help/dns-over-https-and-dns-over-tls"},
  {id:"cloudflare", name:"Cloudflare 1.1.1.1", flag:"🇺🇸 da usare con cautela", lvl:["g"], tag:"Veloce ma centralizzato", desc:"DNS cifrato 1.1.1.1 e app WARP: veloci, gratuiti, un vero progresso rispetto al resolver del tuo provider.", why:"Utile per uso quotidiano, ma Cloudflare siede già davanti a gran parte del web: instradarci anche il DNS concentra ulteriormente le tue tracce presso un'unica azienda USA.", steps:["Bene per uso comune e blocco malware (1.1.1.1 for Families)","Per uso sensibile preferisci Quad9 o Mullvad DNS"], link:"https://one.one.one.one"},
  {id:"pihole", name:"Pi-hole · AdGuard Home", flag:"🌍 open-source", lvl:["r"], tag:"Blocco a livello rete", desc:"Blocca pubblicità e tracker per tutta la rete casalinga insieme, installato su un Raspberry Pi.", why:"Filtra ogni dispositivo di casa, anche quelli dove non si possono installare estensioni: TV, oggetti connessi.", steps:["Su un Raspberry Pi (o container) lancia l'installer ufficiale di Pi-hole","Nelle impostazioni del router indica l'indirizzo del Pi-hole come server DNS"], link:"https://pi-hole.net"}
]},
{id:"vpn", icon:"🛡️", title:"VPN: la verità", intro:"Un VPN non ti protegge dallo scan lato client di Chat Control: quello legge i messaggi sul dispositivo, prima della cifratura e quindi prima del VPN. È utile contro sorveglianza di rete, geolocalizzazione e censura — un pezzo del puzzle, non la soluzione.", items:[
  {id:"mullvadvpn", name:"Mullvad VPN", flag:"🇸🇪 open-source", lvl:["g","y","r"], tag:"Senza account · cash/Monero", desc:"VPN che maschera l'IP e cifra il traffico fino ai suoi server, senza chiedere mai un'informazione personale.", why:"Lo standard oro della privacy: nessuna email, nessun nome, solo un numero di account. Politica no-log verificata, pagamento anche in contanti o Monero.", steps:["Vai su mullvad.net, genera un numero di account (nessuna email richiesta)","Scegli durata e metodo di pagamento (prezzo fisso)","Scarica l'app da mullvad.net/download","Connettiti a un server fuori dal tuo Paese, attiva il kill switch e il DNS Mullvad"], link:"https://mullvad.net"},
  {id:"protonvpn", name:"Proton VPN", flag:"🇨🇭 open-source", lvl:["g"], tag:"Piano gratuito onesto", desc:"Il VPN dell'ecosistema Proton, con un vero piano gratuito (raro e onesto).", why:"Sede svizzera, verificato, open-source. Il piano gratuito è senza pubblicità, senza rivendita dati, senza limite di volume.", steps:["Vai su protonvpn.com e accedi col tuo account Proton","Installa l'app","Usa 'Quick Connect' o scegli un Paese, attiva kill switch e NetShield"], link:"https://protonvpn.com"},
  {id:"ivpn", name:"IVPN", flag:"🇬🇮 open-source", lvl:["y","r"], tag:"Senza email · no-log", desc:"Piccolo provider VPN particolarmente rigoroso e trasparente, sullo stesso modello di Mullvad.", why:"Politica no-log verificata, nessuna email obbligatoria, pagamento in crypto o contanti.", steps:["Su ivpn.net genera un account (nessuna email)","Paga in criptovaluta o contanti","Installa l'app, connettiti fuori UE, attiva kill switch e WireGuard"], link:"https://www.ivpn.net"}
]},
{id:"censura", icon:"🪪", title:"Censura & identità digitale", intro:"Lo stesso pretesto ('proteggere i minori') serve a imporre la verifica d'identità per accedere a internet. È la fine programmata dell'anonimato online — quindi una forma di censura. La contromossa: prendere un IP in un Paese che non impone questi controlli, e procurarsi gli strumenti in modo anonimo.", items:[
  {id:"vpnfuori", name:"VPN fuori giurisdizione", flag:"", lvl:["y","r"], tag:"Azione", desc:"Connettiti a un server fuori dal Paese che filtra (idealmente fuori UE e '14 Eyes'), con politica no-log verificata.", why:"Ti restituisce l'accesso a reti che richiedono un documento d'identità.", steps:["Scegli un server in un Paese senza obblighi di verifica età","Verifica la politica no-log del provider"], link:"#"},
  {id:"pagamentoanonimo", name:"Pagamento anonimo del VPN", flag:"", lvl:["y","r"], tag:"Azione", desc:"Paga il VPN in criptovaluta o contanti (Mullvad, IVPN, Proton lo accettano).", why:"Se un giorno i VPN venissero 'vietati', i processori di pagamento potrebbero rifiutare le carte: contanti e crypto resterebbero le uniche vie.", steps:["Genera un indirizzo di pagamento monouso presso il provider","Invia l'importo esatto da un wallet"], link:"#"},
  {id:"torperbloccati", name:"Tor per recuperare un VPN bloccato", flag:"", lvl:["r"], tag:"Azione", desc:"Se il sito del provider diventa irraggiungibile dal tuo Paese, passa dal Tor Browser (o un indirizzo .onion) per scaricare il client.", why:"Una volta installato, il VPN è molto più veloce per l'uso quotidiano.", steps:["Scarica Tor Browser","Trova l'indirizzo .onion ufficiale del provider"], link:"#"},
  {id:"cambiopaese", name:"Cambiare il Paese dell'account store", flag:"", lvl:["y"], tag:"Azione", desc:"Un account Apple/Google impostato su un altro Paese fa ricomparire le app rimosse dal tuo store locale.", why:"Utile quando un'app viene ritirata localmente per pressioni regolatorie.", steps:["Impostazioni account Apple ID / Google Play > cambia Paese/regione"], link:"#"}
]},
{id:"google", icon:"📤", title:"Lascia Google — la suite Proton", intro:"Google è un unico account che conosce le tue email, agenda, file, spostamenti e ricerche. Si sostituisce l'intera suite. Un solo account Proton (Svizzera, no-profit, open-source) rimpiazza tutto Google con cifratura end-to-end e giurisdizione fuori 'Five Eyes'. Si può migrare gradualmente, servizio per servizio.", items:[
  {id:"g-mail", name:"Gmail → Proton Mail", flag:"", lvl:["g","y","r"], tag:"", desc:"Vedi sezione Email cifrata & PGP.", why:"Primo tassello della migrazione.", steps:["Vedi Proton Mail sopra"], link:"https://proton.me/mail"},
  {id:"g-drive", name:"Google Drive → Proton Drive", flag:"", lvl:["g","y"], tag:"", desc:"Cloud cifrato end-to-end per file e foto.", why:"Proton non può leggere i tuoi file: cifrati prima di lasciare il dispositivo.", steps:["Attiva Proton Drive nel tuo account, installa l'app"], link:"https://proton.me/drive"},
  {id:"g-cal", name:"Google Calendar → Proton Calendar", flag:"", lvl:["g","y"], tag:"", desc:"Agenda cifrata, incluso nello stesso account Proton.", why:"Un solo login per mail, drive e agenda.", steps:["Attivalo dall'app Proton, importa il tuo calendario Google"], link:"https://proton.me/calendar"},
  {id:"g-pass", name:"Google Password Manager → Proton Pass", flag:"", lvl:["g","y"], tag:"", desc:"Vedi sezione Password manager.", why:"Con alias email integrati.", steps:["Vedi Proton Pass sotto"], link:"https://proton.me/pass"},
  {id:"g-vpn", name:"Google One VPN → Proton VPN / Mullvad", flag:"", lvl:["g"], tag:"", desc:"Vedi sezione VPN.", why:"Copre anche questo pezzo della suite.", steps:["Vedi VPN sopra"], link:"#vpn"}
]},
{id:"storage", icon:"💾", title:"Storage cifrato", intro:"", items:[
  {id:"protondrive", name:"Proton Drive", flag:"🇨🇭 E2EE", lvl:["g","y"], tag:"Sostituisce Google Drive / iCloud", desc:"Cloud cifrato end-to-end per file e foto, integrato in Proton.", why:"A differenza di Google Drive o iCloud, Proton non può leggere i tuoi file: sono cifrati prima di lasciare il dispositivo.", steps:["Attiva Proton Drive nel tuo account Proton e installa l'app","Attiva il backup automatico delle foto, disattiva quello di Google/Apple"], link:"https://proton.me/drive"},
  {id:"cryptomator", name:"Cryptomator", flag:"🇩🇪 open-source", lvl:["y","r"], tag:"Cifra prima dell'invio", desc:"Un caveau che cifra i file prima di inviarli su qualsiasi cloud, anche Google Drive o Dropbox.", why:"Il trucco perfetto se devi tenere un cloud esistente: il servizio resta pratico, ma il fornitore vede solo dati cifrati illeggibili.", steps:["Installa Cryptomator (PC e mobile) da cryptomator.org","Crea un 'caveau' nella cartella sincronizzata del tuo cloud, scegli una password forte","Metti i file nel caveau: si cifrano e sincronizzano automaticamente"], link:"https://cryptomator.org"},
  {id:"nextcloud-storage", name:"Nextcloud", flag:"🌍 open-source", lvl:["r"], tag:"Il tuo cloud", desc:"Il tuo cloud personale (file, agenda, contatti, note) ospitato sul tuo server.", why:"Il grado ultimo di controllo: i dati non lasciano mai il tuo hardware. Vedi la sezione Self-hosting.", steps:["Vedi la sezione Self-hosting più sotto"], link:"https://nextcloud.com"}
]},
{id:"password", icon:"🔑", title:"Gestione password", intro:"Una password unica e forte per servizio: è la base di tutta la sicurezza che segue.", items:[
  {id:"bitwarden", name:"Bitwarden", flag:"🌍 open-source", lvl:["g","y","r"], tag:"Il migliore per iniziare", desc:"Un caveau che memorizza, genera e compila le password per te, su tutti i dispositivi.", why:"Gratuito, verificato, multipiattaforma, cifrato end-to-end. Anche auto-ospitabile (via Vaultwarden).", steps:["Crea un account su bitwarden.com, scegli una password master lunga (una frase)","Installa l'estensione browser e l'app mobile","Lascia che Bitwarden salvi e sostituisca le vecchie password con password generate"], link:"https://bitwarden.com"},
  {id:"keepassxc", name:"KeePassXC", flag:"🌍 open-source", lvl:["r"], tag:"100% locale", desc:"Un caveau locale: un file cifrato che solo tu possiedi, senza cloud né account.", why:"Niente lascia il dispositivo, a meno che tu non decida di sincronizzarlo tu stesso (es. via Cryptomator). Scelta dei puristi.", steps:["Installa KeePassXC (PC) e un'app compatibile su mobile (KeePassDX su Android, Strongbox su iOS)","Crea un database protetto da password master","Per averlo su più dispositivi, sincronizza il file via un cloud cifrato"], link:"https://keepassxc.org"},
  {id:"protonpass", name:"Proton Pass", flag:"🇨🇭 open-source", lvl:["g","y"], tag:"Con alias email", desc:"Il gestore password dell'ecosistema Proton, con alias email usa-e-getta integrati.", why:"Ideale se sei già su Proton: un solo account per mail, cloud e password.", steps:["Attivalo dal tuo account Proton, installa l'estensione"], link:"https://proton.me/pass"}
]},
{id:"2fa", icon:"🔐", title:"Doppia autenticazione & chiavi hardware", intro:"Una password, anche forte, può trapelare. La 2FA aggiunge una seconda prova al login. Evita l'SMS: è vulnerabile a SIM-swap e intercettazione di rete (SS7) — usalo solo come ultima risorsa.", items:[
  {id:"yubikey", name:"YubiKey · Nitrokey", flag:"Chiave hardware FIDO2", lvl:["y","r"], tag:"", desc:"Una piccola chiave fisica (USB, spesso NFC) che prova la tua identità con un semplice tocco.", why:"La 2FA più solida: resiste al phishing, perché la chiave verifica l'indirizzo reale del sito prima di rispondere.", steps:["Procurati due chiavi su yubico.com o nitrokey.com (una principale, una di scorta)","Nelle impostazioni sicurezza di ogni account aggiungi una 'chiave di sicurezza' o 'passkey'","Conserva la chiave di scorta in un luogo sicuro separato"], link:"https://www.yubico.com"},
  {id:"aegis", name:"Aegis · Ente Auth", flag:"🌍 open-source", lvl:["g","y","r"], tag:"Codici TOTP", desc:"App che generano i codici a sei cifre che cambiano ogni 30 secondi, in sostituzione di Google Authenticator.", why:"Aegis (Android) tiene i codici in un caveau locale cifrato senza cloud. Ente Auth aggiunge sync cifrata end-to-end tra dispositivi.", steps:["Installa Aegis (F-Droid) o Ente Auth (tutte le piattaforme)","Su ogni account attiva la 2FA 'app di autenticazione' e scansiona il QR","Annota i codici di scorta su carta"], link:"https://getaegis.app"}
]},
{id:"social", icon:"🌍", title:"Social decentralizzati", intro:"Instagram, X e Facebook appartengono ad aziende che ti profilano e possono censurarti o cancellarti da un giorno all'altro. Il 'fediverso' propone reti che appartengono ai loro utenti.", items:[
  {id:"mastodon", name:"Mastodon", flag:"🌍 open-source", lvl:["g","y"], tag:"Sostituisce X / Twitter", desc:"L'alternativa a X/Twitter: migliaia di server indipendenti che comunicano tra loro (il 'fediverso').", why:"Nessun padrone unico, nessun algoritmo che decide al posto tuo, nessun ban arbitrario di un'unica azienda.", steps:["Su joinmastodon.org scegli un server adatto e crea un account","Installa un'app e segui account: vedi tutto il fediverso"], link:"https://joinmastodon.org"},
  {id:"nostr", name:"Nostr", flag:"🌍 protocollo aperto", lvl:["y","r"], tag:"Incensurabile", desc:"Non un'app ma un protocollo: identità come semplice coppia di chiavi, come Bitcoin.", why:"Zero email, zero password, nessun account cancellabile. Nessuno può bannarti in modo definitivo.", steps:["Installa un client: Damus (iPhone), Amethyst o Primal (Android)","L'app genera la coppia di chiavi: salva la chiave privata (nsec) su carta, mai condivisa","Crea il profilo, segui persone, attiva gli zap"], link:"https://nostr.com"},
  {id:"matrix", name:"Matrix / Element", flag:"🌍 federato · E2EE", lvl:["y","r"], tag:"Sostituisce Discord / Slack", desc:"Chat di comunità in stile Discord o Slack, ma federata e cifrabile end-to-end.", why:"Puoi ospitare il tuo server (Synapse) e controllare i tuoi dati. Attenzione: in federazione i server vedono appartenenza alle stanze e orari.", steps:["Installa Element (element.io), crea un account su un server pubblico o il tuo","Attiva la cifratura end-to-end per le conversazioni private"], link:"https://element.io"},
  {id:"fediverse-rest", name:"Pixelfed · PeerTube · Lemmy", flag:"🌍 open-source", lvl:["y"], tag:"Insta · YouTube · Reddit", desc:"I cugini federati di Instagram, YouTube e Reddit.", why:"Stessa logica di Mastodon: nessun proprietario unico, nessun algoritmo pubblicitario, nessun tracciamento.", steps:["Scegli l'istanza che preferisci per ciascun servizio e crea un account"], link:"https://pixelfed.org"}
]},
{id:"soldi", icon:"💰", title:"Sovranità finanziaria", intro:"Anche il denaro è sorvegliato e censurabile: conti di attivisti congelati, donazioni bloccate, ogni pagamento con carta tracciato. La privacy finanziaria è legale — non va confusa con l'evasione fiscale.", items:[
  {id:"bitcoin", name:"Bitcoin (auto-custodia)", flag:"", lvl:["y","r"], tag:"Resistente alla censura", desc:"Moneta digitale che detieni tu stesso, senza passare da una banca.", why:"In auto-custodia (le chiavi in un wallet che controlli solo tu), nessuno può congelare i tuoi fondi.", steps:["Procurati bitcoin (exchange o tra privati)","Trasferiscili subito in un wallet che controlli tu (hardware wallet o app open-source)","Salva la frase di recupero su carta, mai in foto o online"], link:"https://bitcoin.org"},
  {id:"monero", name:"Monero (XMR)", flag:"", lvl:["r"], tag:"Privato di default", desc:"La criptovaluta della privacy: importi, mittente e destinatario mascherati di default.", why:"L'esatto opposto di Bitcoin su questo punto: transazioni riservate per progettazione.", steps:["Installa un wallet (getmonero.org o Cake Wallet su mobile)","Ottieni XMR via un exchange decentralizzato","Salva la frase di recupero su carta"], link:"https://www.getmonero.org"}
]},
{id:"ia", icon:"🤖", title:"IA conversazionale", intro:"Ciò che scrivi in un'IA cloud è una confessione scritta, datata e conservata. Le offerte consumer si addestrano sui tuoi dati di default, e cancellare una chat non garantisce la sua rimozione. Regola semplice: mai incollare in un'IA cloud ciò che non diresti a uno sconosciuto che registra.", items:[
  {id:"localai", name:"Ollama · LM Studio · Jan · GPT4All", flag:"🌍 100% locale", lvl:["y","r"], tag:"Sostituisce ChatGPT", desc:"Software per far girare un modello IA direttamente sul tuo computer.", why:"Le domande non lasciano mai il dispositivo: nessun server, nessun account, nessuna telemetria, funziona offline.", steps:["Per iniziare: installa LM Studio o Jan (interfaccia grafica)","Scarica un modello adatto alla potenza della tua macchina (es. Llama, Mistral)","Chatta: tutto avviene in locale"], link:"https://lmstudio.ai"},
  {id:"cloudai", name:"Duck.ai · Lumo (Proton)", flag:"", lvl:["g","y"], tag:"Cloud orientato alla privacy", desc:"Accesso IA in cloud ma pensato per la privacy, quando un'IA locale non è praticabile.", why:"Duck.ai dà accesso anonimizzato a più modelli. Lumo (Proton) cifra gli scambi e non li usa per addestrare.", steps:["Usa duck.ai o lumo.proton.me per argomenti non sensibili"], link:"https://duck.ai"}
]},
{id:"toolbox", icon:"🧰", title:"La cassetta degli attrezzi quotidiana", intro:"Google e Apple non sono solo email: mappe, note, agenda, foto, videochiamate, tutto è legato alla tua identità. Si sostituisce ogni pezzo, uno alla volta.", items:[
  {id:"maps", name:"Organic Maps · OsmAnd", flag:"🌍 open-source", lvl:["g","y","r"], tag:"Sostituisce Google Maps", desc:"App di mappe e navigazione basate su OpenStreetMap, funzionano offline.", why:"Google Maps registra ogni tuo spostamento. Organic Maps non traccia nulla e non mostra pubblicità.", steps:["Installa da F-Droid, App Store o Play Store","Scarica in anticipo le mappe delle regioni che ti servono"], link:"https://organicmaps.app"},
  {id:"notes", name:"Standard Notes · Joplin · CryptPad", flag:"🌍 open-source", lvl:["g","y"], tag:"Sostituisce Docs / Notion", desc:"Note e documenti cifrati end-to-end, per sostituire Google Docs, Notion o Evernote.", why:"Standard Notes (di Proton) cifra le note di default. CryptPad offre l'equivalente di Google Docs in tempo reale, interamente cifrato.", steps:["Crea un account, installa l'app, attiva la cifratura","CryptPad: usa cryptpad.org, nessun account richiesto per iniziare"], link:"https://standardnotes.com"},
  {id:"video", name:"Jitsi Meet · Element Call", flag:"🌍 open-source", lvl:["g","y"], tag:"Sostituisce Zoom / Meet", desc:"Videoconferenze senza account né installazione pesante, per sostituire Zoom, Meet o Teams.", why:"Jitsi Meet si avvia nel browser, senza account, ed è auto-ospitabile.", steps:["Jitsi: vai su meet.jit.si, crea un nome stanza, condividi il link","Element Call: dall'app Element avvia una chiamata in una stanza"], link:"https://jitsi.org"},
  {id:"photos", name:"Ente · Immich", flag:"🌍 open-source", lvl:["y","r"], tag:"Sostituisce Google Photos", desc:"Due modi per tenere le tue foto senza affidarle a Google o Apple.", why:"Ente è un servizio gestito, cifrato end-to-end. Immich è un clone di Google Photos che ospiti tu stesso.", steps:["Ente: installa l'app, crea un account, attiva il backup automatico","Immich: distribuiscilo sul tuo server via Docker (vedi Self-hosting)"], link:"https://ente.io"},
  {id:"alias", name:"SimpleLogin · addy.io", flag:"🌍 open-source", lvl:["g","y","r"], tag:"Alias email", desc:"Alias email usa-e-getta: un indirizzo unico per sito, che reindirizza alla tua vera casella senza mai rivelarla.", why:"Se un sito viene violato o ti spamma, disattivi quell'alias e sai subito chi ha fatto trapelare i tuoi dati.", steps:["Crea un account, installa l'estensione browser","A ogni registrazione genera un nuovo alias invece del vero indirizzo"], link:"https://simplelogin.io"},
  {id:"backup", name:"Backup cifrati (Cryptomator · restic)", flag:"🌍 open-source", lvl:["y","r"], tag:"", desc:"Backup di telefono e computer cifrando i dati prima che partano verso un cloud.", why:"I backup iCloud/Google sono spesso accessibili al fornitore, e quindi alla giustizia. Regola d'oro: due copie cifrate, due supporti, due luoghi.", steps:["iPhone: Impostazioni > il tuo nome > iCloud > Protezione avanzata dati: attivala","PC: installa Cryptomator, crea un caveau, mettici i file prima di sincronizzare"], link:"https://cryptomator.org"},
  {id:"gdpr", name:"Cancella i tuoi dati (GDPR)", flag:"", lvl:["y"], tag:"Diritto all'oblio", desc:"Far rimuovere le tue informazioni personali dai 'data broker' che le raccolgono e rivendono.", why:"In Europa il GDPR (art. 17) dà un diritto alla cancellazione, gratuito, in genere entro un mese.", steps:["Richiesta manuale: scrivi al broker citando l'art. 17 GDPR e chiedi la cancellazione","Per automatizzare: servizi come Incogni inviano le richieste per te (a pagamento)"], link:"https://www.garanteprivacy.it"}
]},
{id:"avanzato", icon:"🖥️", title:"Livello avanzato — self-hosting, Tor, OS liberi, OPSEC", intro:"Il grado ultimo di sovranità: ospitare i propri servizi, navigare in modo anonimo, controllare l'hardware stesso. Sezione per profili 🔴 avanzati, ma ogni voce è utile da conoscere.", items:[
  {id:"yunohost", name:"YunoHost · Umbrel · Start9", flag:"🌍 open-source", lvl:["r"], tag:"Server chiavi in mano", desc:"Sistemi che trasformano un vecchio PC o un Raspberry Pi in un server personale, con un catalogo di app installabili in pochi click.", why:"YunoHost gestisce anche la tua email e un login unico. I tuoi dati vivono sul tuo hardware, sotto la giurisdizione che scegli tu.", steps:["Scegli un dispositivo dedicato (Raspberry Pi, mini PC)","Installa YunoHost/Umbrel seguendo la guida ufficiale","Aggiungi app dal catalogo: Nextcloud, Vaultwarden, Immich..."], link:"https://yunohost.org"},
  {id:"tor", name:"Tor Browser · Tails", flag:"🌍 open-source", lvl:["y","r"], tag:"Anonimato di rete", desc:"Tor Browser instrada il traffico su tre relè cifrati, nascondendo chi sei al sito visitato. Tails è un sistema operativo live che non lascia traccia sul computer usato.", why:"Indispensabile per accedere a contenuti censurati, comunicare con fonti sensibili, o navigare da un computer non fidato.", steps:["Scarica Tor Browser da torproject.org","Per sessioni ad alto rischio: avvia Tails da una chiavetta USB, nessun dato resta sul PC"], link:"https://torproject.org"},
  {id:"grapheneos", name:"GrapheneOS · CalyxOS", flag:"Android · open-source", lvl:["r"], tag:"Sistema operativo libero", desc:"Sistemi operativi mobili senza servizi Google, con un modello di sicurezza rinforzato, installabili su Pixel supportati.", why:"Se l'OS stesso impone lo scan, nessuna app può proteggerti: riprendere il controllo del dispositivo è la base di tutto il resto.", steps:["Verifica la compatibilità del tuo dispositivo (grapheneos.org)","Segui la guida ufficiale di installazione (flash via web installer)","Installa le app necessarie via F-Droid o Sandboxed Google Play (opzionale)"], link:"https://grapheneos.org"},
  {id:"opsec", name:"Compartimentazione & OPSEC", flag:"", lvl:["r"], tag:"Disciplina, non solo strumenti", desc:"Non riusare mai username, foto o stile di scrittura tra identità diverse. Ripulisci i metadati dai file prima di condividerli (EXIF).", why:"Il più delle deanonimizzazioni non nascono da un bug tecnico, ma da un errore umano di riuso dell'identità.", steps:["Un'identità = un dispositivo o profilo separato, mai mescolare","Rimuovi metadati EXIF da foto/documenti prima di pubblicarli","Per la trasmissione di documenti sensibili a una redazione: usa SecureDrop o GlobaLeaks"], link:"#"}
]},
{id:"azione", icon:"📢", title:"Passa all'azione", intro:"La tecnologia da sola non basta: il quadro legale si decide in Parlamento europeo. Ogni voce qui è un'azione civica, non un download.", items:[
  {id:"contattaeuro", name:"Contatta il tuo eurodeputato", flag:"", lvl:["g","y","r"], tag:"Azione civica", desc:"Scrivi al tuo rappresentante al Parlamento europeo per chiedere il rigetto di Chat Control 2.0 (CSAR).", why:"Il 5° trilogo è fallito il 29 giugno 2026: le trattative continuano, ogni pressione pubblica conta.", steps:["Trova il tuo eurodeputato su europarl.europa.eu","Scrivi un messaggio breve, personale, chiedendo la sua posizione pubblica"], link:"https://www.europarl.europa.eu"},
  {id:"edri", name:"Sostieni EDRi · Patrick Breyer", flag:"", lvl:["g","y"], tag:"Azione civica", desc:"Organizzazioni e figure che seguono da vicino il dossier Chat Control e coordinano le campagne di opposizione.", why:"Informazione aggiornata e strumenti di pressione pronti all'uso (lettere modello, tracker del voto).", steps:["Iscriviti alla newsletter di EDRi o del sito di Patrick Breyer","Condividi gli aggiornamenti con la tua rete"], link:"https://edri.org"},
  {id:"donazioni", name:"Sostieni gli strumenti che usi", flag:"", lvl:["g","y","r"], tag:"Azione civica", desc:"Signal Foundation, Tor Project, Mullvad, Proton, F-Droid: sono no-profit o realtà indipendenti che vivono di donazioni e abbonamenti.", why:"Chi paga un servizio ne è il cliente, non il prodotto. Sostenerli economicamente è un voto diretto per un'infrastruttura libera.", steps:["Valuta una donazione ricorrente, anche piccola, a Signal Foundation o Tor Project","Preferisci gli abbonamenti a pagamento di Proton/Mullvad rispetto ai piani gratuiti se te lo puoi permettere"], link:"https://signal.org/donate"}
]}
];
